Settings:
  # 禁用的自定义物品处理器 ID 列表，被列出的物品将以普通物品形式上架
  # https://nightexpressdev.com/economy-bridge/items/
  Disabled_Item_Handlers:
  - mmoitems

  # 拍卖行不可使用的世界列表
  # [*] 区分大小写！
  Disabled_Worlds:
  - another_world
  - custom_world

  # 以下游戏模式的玩家无法将物品上架拍卖行
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/GameMode.html
  Disabled_Gamemodes:
  - CREATIVE

  # 玩家加入服务器时，若有未领取的售出物品，是否发送提示消息
  Notify_Unclaimed_On_Join: true

  # 玩家加入服务器时，若有已过期的上架物品，是否发送提示消息
  Notify_Expired_On_Join: true

  Listings:
    # 若为 true，将隐藏拍卖物品的属性（伤害、耐久等）
    Hide_Attributes: false

    # 物品在拍卖行中未售出时的最大上架时长（秒）
    # 到期后玩家仍可在拍卖 GUI 的“过期物品”中领取，但需在 Purge_In 设定时间内，否则永久删除
    # [*] 仅对新上架的物品生效
    # [默认 604800 秒（7 天）]
    Expire_In: 604800

    # 已过期/已售出但未领取的物品在彻底删除前的保留时间（秒）
    # 玩家可在拍卖 GUI 中领取或取回这些物品
    # [*] 仅对新产生的物品生效
    # [默认 604800 秒（7 天）]
    Purge_In: 604800

    # 玩家上架新物品时，是否向全服广播消息
    Announce: true

    # 根据玩家权限组或权限节点，限制其最大同时上架物品数量
    # 使用 -1 表示无限制
    Listings_Per_Rank:
      # 取值方式：RANK（权限组） / PERMISSION（权限节点）
      # ==================== RANK 模式 ====================
      # 根据玩家所在权限组匹配，未匹配到任何组时使用 Default_Value
      #   Values:
      #     vip: 1   # 玩家需属于 'vip' 权限组
      #     gold: 2  # 玩家需属于 'gold' 权限组
      #     emerald: 3 # 玩家需属于 'emerald' 权限组
      #
      # ==================== PERMISSION 模式 ====================
      # 根据玩家拥有的权限节点匹配，权限节点为 Permission_Prefix 前缀 + Values 中的键
      # 若未匹配到任何节点，使用 Default_Value
      #   Permission_Prefix: 'example.prefix.'
      #   Values:
      #     vip: 1   # 需拥有 'example.prefix.vip' 权限
      #     gold: 2  # 需拥有 'example.prefix.gold' 权限
      #     emerald: 3 # 需拥有 'example.prefix.emerald' 权限
      Mode: RANK
      # PERMISSION 模式下权限节点前缀
      Permission_Prefix: auction.listings.amount.
      Default_Value: 10
      Values:
        gold: 20
        vip: 15
        admin: -1

    # 已售出的物品是否自动领取（仅当卖家在线时生效）
    AutoClaim: false

    Price:
      # 若为 true，上架价格将自动取整，去掉小数
      Round_To_Integer: false

      # 为特定货币设定最小/最大允许价格
      # 使用 -1 表示无限制
      # 使用 'default' 为所有未列出的货币指定默认值
      # 若未列出且未定义 'default'，则无限制
      Per_Currency:
        vault:
          Min: 1.0
          Max: 1.0E7
        default:
          Min: -1.0
          Max: -1.0

      # 为特定物品/方块设定最小/最大允许价格
      # 使用 -1 表示无限制
      # 物品/方块名：https://minecraft.wiki/w/Java_Edition_data_values -> 资源位置（Resource location）
      Per_Material:
        dirt:
          Min: 1.0
          Max: 15.0
        diamond:
          Min: 500.0
          Max: -1.0
        emerald:
          Min: 300.0
          Max: -1.0

    Tax:
      # 上架时收取的税费比例（百分比）
      # 例：玩家想以 50 元上架物品，税率为 10%，需额外支付 5 元
      On_Listing_Add: 10.0

      # 领取售出物品收益时的税费比例（百分比）
      # 例：物品以 50 元售出，税率为 10%，最终可领取 45 元
      On_Listing_Purchase: 0.0

    # 禁止上架到拍卖行的物品列表
    # 原版物品名：https://minecraft.wiki/w/Java_Edition_data_values -> 资源位置（Resource location）
    # 支持的插件：ExcellentCrates, ExecutableItems, ItemsAdder, MMOItems, Nexo, Oraxen
    Disabled_Materials:
    - bedrock
    - barrier
    - custom_item_name
    - flame_sword

    # 物品名称中包含以下文本将无法上架
    Disabled_Names:
    - bad text
    - badword

    # 物品 Lore 中包含以下文本将无法上架
    Disabled_Lores:
    - bad text line
    - badword

    # 禁止上架的物品模型数据值（Model Data）列表
    Disabled_Models:
      DIAMOND_HELMET: 1016,1002
      NETHERITE_SWORD: 1015,1001

Menu:
  # 购买成功后是否重新打开拍卖 GUI，而非关闭
  ReOpen_On_Purchase: true

  Container_Preview:
    # 是否在拍卖 GUI 中启用容器预览功能
    # 允许玩家在购买前查看潜影盒、箱子、木桶等内部内容
    # 使用右键（RMB）操作
    Enabled: true
    # 预览 GUI 的标题
    Title: 预览

Database:
  # 数据库类型
  # 可选值：MYSQL, SQLITE
  Type: SQLITE

  # 远程数据库数据同步间隔（秒）
  # 仅对 MYSQL 有效；设为 -1 关闭
  Sync_Interval: -1

  # 数据库表前缀
  Table_Prefix: excellentshop_auction

  MySQL:
    # 数据库用户名
    Username: root
    # 数据库密码
    Password: root
    # 数据库地址，格式：主机:端口
    Host: localhost:3306
    # 插件使用的数据库名
    Database: minecraft
    # 连接选项，非必要请勿修改
    Options: ?allowPublicKeyRetrieval=true&useSSL=false

  SQLite:
    # SQLite 数据库文件名（可包含路径）
    FileName: data.db

  Purge:
    # 是否启用数据清理（Purge）
    # 将删除超过指定时间的数据库记录
    Enabled: false
    # 记录最大保留时间（天）
    # 具体行为由插件定义，默认指玩家不活跃天数
    For_Period: 60