Name: 装饰品  # 商店名称
Description:  # 商店描述
- <lgray>用鲜花、树叶等物品</lgray>
- <lgray>装饰您的建筑！</lgray>
- ' '
- <c:#E78A8A>→ <b><u>点击</u></b> 浏览</c>
Icon:  # 图标设置
  Material: minecraft:player_head  # 材质：玩家头颅
  Display_Name: <c:#E78A8A><b>装饰品</b></c>  # 显示名称
  Lore: []  # 物品说明（空）
  SkinURL: 3052520ee99b6fcdbe70ed1f7cfbc3fb7175f04a2ceb007c9b11d8d727bca044  # 皮肤URL
Pages: 4  # 页面数量
Permission_Required: false  # 是否需要权限
Transaction_Allowed:  # 允许的交易类型
  BUY: true   # 允许购买
  SELL: true  # 允许出售
MainMenu:  # 主菜单设置
  Slot: 32  # 槽位编号
Aliases: []  # 别名（空）
Layout:  # 布局设置
  Name: default  # 布局名称：默认
