Name: 彩色方块  # 商店名称
Description:  # 商店描述
- <lgray>用不同颜色的方块</lgray>
- <lgray>美化您的建筑。</lgray>
- ' '
- <c:#FF7222>→ <b><u>点击</u></b> 浏览</c>
Icon:  # 图标设置
  Material: minecraft:player_head  # 材质：玩家头颅
  Display_Name: <c:#FF7222><b>彩色方块</b></c>  # 显示名称
  Lore: []  # 物品说明（空）
  SkinURL: 7a7d6c0accd2e9ccaefa96b9438d6e202fec795acf7072bcfd9cd9d4b5a32b0e  # 皮肤URL
Pages: 11  # 页面数量
Permission_Required: false  # 是否需要权限
Transaction_Allowed:  # 允许的交易类型
  BUY: true   # 允许购买
  SELL: true  # 允许出售
MainMenu:  # 主菜单设置
  Slot: 12  # 槽位编号
Aliases: []  # 别名（空）
Layout:  # 布局设置
  Name: default  # 布局名称：默认
