General:
  DateFormat: MM/dd/yyyy HH:mm
  # 控制玩家是否需要拥有 'excellentshop.currency.[name]' 权限才能使用特定货币开设商店或上架商品。
  # [*] 仅对 ChestShop 和 Auction 模块有效。
  # [*] 设置为默认的货币始终允许使用。
  Currency_Need_Permission: false
  # 设置插件检查商店“更新”的频率（单位：秒），例如：
  # - 轮换商店的轮换时间。
  # - 静态商店的可用折扣。
  # - 虚拟商店和静态商店浮动价格的更新时间。
  # 除非您知道自己在做什么，否则不要修改。
  # [默认值为 60 秒]
  Shop_Update_Interval: 60
  # 设置当玩家背包已满时是否可以继续购买商品。
  Buy_With_Full_Inventory: false
  # 设置当玩家完成交易后是否关闭商店 GUI。
  Close_GUI_After_Trade: false
GUI:
  # [已过时。GUI 文件中已有专门的 PlaceholderAPI 设置]
  Use_PlaceholderAPI: false
  # 设置在商店 GUI 中对商品点击的操作。
  # 允许的点击类型：https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/inventory/ClickType.html
  # 允许的值：BUY_SELECTION, SELL_SELECTION, SELL_ALL, BUY_SINGLE, SELL_SINGLE, PURCHASE_OPTION, UNDEFINED
  Click_Types:
    SHIFT_RIGHT: SELL_SINGLE
    RIGHT: SELL_SELECTION
    SWAP_OFFHAND: SELL_ALL
    SHIFT_LEFT: BUY_SINGLE
    LEFT: BUY_SELECTION
Data:
  # 设置修改后的商品和商店数据保存到数据库的频率（单位：秒）。
  # 包括以下数据：
  # - 商品价格数据（浮动、动态）。
  # - 商品库存数据（全局、玩家）。
  # - 商店轮换数据。
  # [*] 服务器重启或插件重载时也会保存数据。
  # [*] 如果您使用 SQLite 或不关心多服务器同步，可以禁用此功能。
  SaveInterval: 5
  PriceTable: price_data
  StocksTable: stocks
  RotationsTable: rotations
# 模块设置。
Module:
  auction:
    # 控制模块是否启用。
    Enabled: true
    # 创建模块专用命令及其别名。
    # [*] 需要重启服务器才能生效。
    Command_Aliases: auction,auc,ah
    # 设置模块消息的前缀。
    Prefix: 拍卖
    Currency:
      # 设置模块的默认货币。
      # 可用货币列表：https://nightexpressdev.com/excellentshop/features/multi-currency
      Default: vault
      # 设置模块启用的货币。
      # 使用 '*' 表示启用所有可用货币。
      # 可用货币列表：https://nightexpressdev.com/excellentshop/features/multi-currency
      # [*] 默认货币始终启用。
      Enabled:
      - '*'
  chest_shop:
    # 控制模块是否启用。
    Enabled: true
    # 创建模块专用命令及其别名。
    # [*] 需要重启服务器才能生效。
    Command_Aliases: chestshop,cshop,playershop,pshop
    # 设置模块消息的前缀。
    Prefix: 玩家商店
    Currency:
      # 设置模块的默认货币。
      # 可用货币列表：https://nightexpressdev.com/excellentshop/features/multi-currency
      Default: vault
      # 设置模块启用的货币。
      # 使用 '*' 表示启用所有可用货币。
      # 可用货币列表：https://nightexpressdev.com/excellentshop/features/multi-currency
      # [*] 默认货币始终启用。
      Enabled:
      - '*'
  virtual_shop:
    # 控制模块是否启用。
    Enabled: true
    # 创建模块专用命令及其别名。
    # [*] 需要重启服务器才能生效。
    Command_Aliases: virtualshop,vshop
    # 设置模块消息的前缀。
    Prefix: 商店
    Currency:
      # 设置模块的默认货币。
      # 可用货币列表：https://nightexpressdev.com/excellentshop/features/multi-currency
      Default: vault
      # 设置模块启用的货币。
      # 使用 '*' 表示启用所有可用货币。
      # 可用货币列表：https://nightexpressdev.com/excellentshop/features/multi-currency
      # [*] 默认货币始终启用。
      Enabled:
      - '*'