# ==================== [SECTION] 设置 ====================
# > [MenuType] : String | 菜单类型。可用值：https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/MenuType.html
# > [Title] : String | 菜单标题
# > [Auto_Refresh] : Integer | 自动刷新间隔（秒），设为 0 关闭
# > [PlaceholderAPI -> Enabled] : Boolean | 启用后按玩家解析所有物品的 PlaceholderAPI 变量
#
# ==================== [SECTION] 内容 ====================
# 可自由增删或修改本节中的物品
# > [Item] : 配置段 | 物品设置
#     [*] 详见：https://nightexpressdev.com/nightcore/configuration/item-formation/
# > [Priority] : Integer | 物品优先级，数值高者覆盖同槽位其他物品
# > [Slots] : 整数列表 | 物品槽位，从 0 开始，用逗号分隔
#     Slots: '0,4,9,10'
# > [Type] : String | 定义点击动作
#     [*] 可用：['close','shop_change_name','shop_change_products','list_shops','list_owner_shops','shop_bank','shop_display','shop_rent_settings','shop_rent_extend','set_admin_shop','set_player_shop','shop_delete','rent_cancel','shop_buying','shop_selling','shop_change_type','shop_storage']
# > [Click_Commands] : 配置段 | 点击时执行指令，支持 PlaceholderAPI
#     [*] 仅当 [Type] 为空时生效
#     [*] 支持点击类型：[LEFT, RIGHT, SHIFT_LEFT, SHIFT_RIGHT, DROP_KEY, SWAP_KEY, DRAG_N_DROP]
#     [*] 使用前缀 'player:' 以玩家身份执行
#     Click_Commands:
#       LEFT:
#       - say Hello
#       - give %player_name% diamond 1
#       - player: warp shop
# ==================================================
Settings:
  MenuType: generic_9x6
  Title: <black>%shop_name%</black>
  Auto_Refresh: -1
  PlaceholderAPI:
    Enabled: false

Content:
  shop_change_name:
    Priority: 10
    Item:
      Material: minecraft:name_tag
      Display_Name: <lyellow><b>商店名称</b></lyellow>
      Lore:
      - '<lyellow>➥ <gray>当前: </gray>%shop_name%</lyellow>'
      - ''
      - <gray>玩家看到的商店名称，</gray>
      - <gray>用于悬浮字与 GUI。</gray>
      - ''
      - <lyellow>→ <u>点击修改</u></lyellow>
      Hide_Components: true
    Slots: '10'
    Type: shop_change_name

  shop_change_products:
    Priority: 10
    Item:
      Material: minecraft:item_frame
      Display_Name: <lyellow><b>商品管理</b></lyellow>
      Lore:
      - <gray><lyellow>➥ </lyellow>当前: <lyellow>%shop_products%</lyellow>/<lyellow>%max_products%</lyellow> 个商品</gray>
      - ''
      - <gray>在此处修改价格、添加物品</gray>
      - <gray>与补货。</gray>
      - ''
      - <lyellow>→ <u>点击打开</u></lyellow>
      Hide_Components: true
    Slots: '13'
    Type: shop_change_products

  list_shops:
    Priority: 10
    Item:
      Material: minecraft:chest
      Display_Name: <lyellow><b>我的商店</b></lyellow>
      Lore:
      - <gray><lyellow>➥ </lyellow>您已拥有 <lyellow>%shops_amount%</lyellow>/<lyellow>%max_shops%</lyellow> 家商店</gray>
      - ''
      - <gray>查看您创建/租赁的全部商店。</gray>
      - ''
      - <lyellow>→ <u>点击打开</u></lyellow>
      Hide_Components: true
    Slots: '16'
    Type: list_shops

  list_owner_shops:
    Priority: 10
    Item:
      Material: minecraft:chest
      Display_Name: <lyellow><b>%shop_owner% 的商店</b></lyellow>
      Lore:
      - <gray>查看由 <lyellow>%shop_owner%</lyellow> 创建的</gray>
      - <gray>全部商店。</gray>
      - ''
      - <lyellow>→ <u>点击打开</u></lyellow>
      Hide_Components: true
    Slots: '16'
    Type: list_owner_shops

  shop_bank:
    Priority: 10
    Item:
      Material: minecraft:emerald
      Display_Name: <lgreen><b>商店银行</b></lgreen>
      Lore:
      - '<gray><lgreen>➥ </lgreen>余额: <lgreen>%shop_bank_balance%</lgreen></gray>'
      - ''
      - <gray>向银行注资，用于向玩家</gray>
      - <gray><lred>收购</lred> 物品。</gray>
      - <gray>从银行提取出售所得。</gray>
      - ''
      - <lgreen>→ <u>点击打开</u></lgreen>
      Hide_Components: true
    Slots: '28'
    Type: shop_bank

  shop_display:
    Priority: 10
    Item:
      Material: minecraft:beacon
      Display_Name: <lcyan><b>外观设置</b></lcyan>
      Lore:
      - '<lcyan>➥ <gray>悬浮字: </gray>%shop_hologram_enabled%</lcyan>'
      - '<lcyan>➥ <gray>展示台: </gray>%shop_showcase_enabled%</lcyan>'
      - ''
      - <gray>开关悬浮字、自定义展示台颜色。</gray>
      - ''
      - <lcyan>→ <u>点击打开</u></lcyan>
      Hide_Components: true
    Slots: '31'
    Type: shop_display

  shop_rent_settings:
    Priority: 10
    Item:
      Material: minecraft:jungle_sign
      Display_Name: <lorange><b>租赁设置</b></lorange>
      Lore:
      - '<lorange>➥ <gray>租赁者: </gray>%shop_rented_by%</lorange>'
      - '<lorange>➥ <gray>剩余: </gray>%shop_rent_expires_in%</lorange>'
      - ''
      - <gray>让玩家可租赁此商店，</gray>
      - <gray>设置租金与时长。</gray>
      - ''
      - <lorange>→ <u>点击打开</u></lorange>
      Hide_Components: true
    Slots: '34'
    Type: shop_rent_settings

  shop_rent_extend:
    Priority: 15
    Item:
      Material: minecraft:gold_nugget
      Display_Name: <yellow><b>续租</b></yellow>
      Lore:
      - '<yellow>➥ <gray>剩余: </gray>%shop_rent_expires_in%</yellow>'
      - '<yellow>➥ <gray>周期: </gray>%shop_rent_duration%</yellow>'
      - '<yellow>➥ <gray>价格: </gray>%shop_rent_price%</yellow>'
      - ''
      - <gray>续租以继续在此经营。</gray>
      - ''
      - <yellow>→ <u>点击续租</u></yellow>
      Hide_Components: true
    Slots: '34'
    Type: shop_rent_extend

  set_admin_shop:
    Priority: 10
    Item:
      Material: minecraft:campfire
      Display_Name: <lyellow><b>玩家商店</b></lyellow>
      Lore:
      - <gray><lyellow>✔ </lyellow>当前为 <lyellow>玩家商店</lyellow>。</gray>
      - ''
      - <gray>玩家商店资金与资源有限，</gray>
      - <gray>需玩家自行管理。</gray>
      - ''
      - <lyellow>→ <u>点击改为管理员商店</u></lyellow>
      Hide_Components: true
    Slots: '45'
    Type: set_admin_shop

  set_player_shop:
    Priority: 10
    Item:
      Material: minecraft:soul_campfire
      Display_Name: <cyan><b>管理员商店</b></cyan>
      Lore:
      - <gray><cyan>✔ </cyan>当前为 <cyan>管理员商店</cyan>。</gray>
      - ''
      - <gray>管理员商店资金与资源无限，</gray>
      - <gray>可独立运行。</gray>
      - ''
      - <cyan>→ <u>点击改为玩家商店</u></cyan>
      Hide_Components: true
    Slots: '45'
    Type: set_player_shop

  shop_delete:
    Priority: 10
    Item:
      Material: minecraft:barrier
      Display_Name: <red><b>删除商店</b></red>
      Lore:
      - <gray>永久删除此商店。</gray>
      - ''
      - <red>→ <u>点击删除</u></red>
      Hide_Components: true
    Slots: '53'
    Type: shop_delete

  rent_cancel:
    Priority: 15
    Item:
      Material: minecraft:barrier
      Display_Name: <red><b>取消租赁</b></red>
      Lore:
      - '<red>➥ <gray>剩余: </gray>%shop_rent_expires_in%</red>'
      - ''
      - <gray>取消您对此商店的租赁。</gray>
      - ''
      - <red>→ <u>点击取消</u></red>
      Hide_Components: true
    Slots: '53'
    Type: rent_cancel

  close:
    Priority: 10
    Item:
      Material: minecraft:iron_door
      Display_Name: <lred><u>退出</u></lred>
      Lore:
      - '%empty-if-above%'
      - '%empty-if-below%'
    Slots: '49'
    Type: close

  black_stained_glass_pane:
    Priority: 0
    Item:
      Material: minecraft:black_stained_glass_pane
      Lore: []
      Hide_Tooltip: true
    Slots: 45,46,47,48,49,50,51,52,53
    Type: 'null'