Name: 药水  # 商店名称
Description:  # 商店描述
- <lgray>使用药水和带效果的箭</lgray>
- <lgray>让自己变得更强！</lgray>
- ' '
- <c:#56FF5C>→ <b><u>点击</u></b> 浏览</c>
Icon:  # 图标设置
  Material: minecraft:player_head  # 材质：玩家头颅
  Display_Name: <c:#56FF5C><b>药水与箭</b></c>  # 显示名称
  Lore: []  # 物品说明（空）
  SkinURL: 42f57c9eed9f90b7c33b0a447568150cb7b5ec62afddf280b4f981ffd480a766  # 皮肤URL
Pages: 4  # 页面数量
Permission_Required: false  # 是否需要权限
Transaction_Allowed:  # 允许的交易类型
  BUY: true   # 允许购买
  SELL: true  # 允许出售
MainMenu:  # 主菜单设置
  Slot: 21  # 槽位编号
Aliases: []  # 别名（空）
Layout:  # 布局设置
  Name: default  # 布局名称：默认
