# ==================== [设置] 配置段 ====================
# > [MenuType] : 字符串 | 代表菜单类型。允许的值: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/MenuType.html
# > [Title] : 字符串 | 设置菜单标题。
# > [Auto_Refresh] : 整数 | 定义菜单刷新频率（秒）。设置为0禁用。
# > [PlaceholderAPI -> Enabled] : 布尔值 | 启用后，为菜单中的所有物品应用PlaceholderAPI占位符（每个玩家）。
#  
# ==================== [内容] 配置段 ====================
# 您可以在此部分自由编辑物品（添加、删除、修改物品）。
# > [Item] : 段落 | 要显示的物品。
#     [*] 导航到 https://nightexpressdev.com/nightcore/configuration/item-formation/ 查看可用选项列表。
# > [Priority] : 整数 | 物品优先级。较高的值将覆盖相同槽位中的其他物品。
# > [Slots] : 整数数组 | 物品槽位，从0开始。用逗号分隔。
#     Slots: '0,4,9,10'
# > [Type] : 字符串 | 定义物品点击操作。
#     [*] 可用类型: ['close', 'confirm', 'decline', 'add_1', 'add_8', 'add_16', 'take_1', 'take_8', 'take_16', 'set_1', 'set_max', 'set_custom', 'set_8', 'set_16', 'add_32', 'take_32', 'set_32', 'add_64', 'take_64', 'set_64']
# > [Click_Commands] : 段落 | 点击时执行命令，支持PlaceholderAPI。
#     [*] 仅在[Type]未设置（null）时有效。
#     [*] 可用点击类型: [LEFT, RIGHT, SHIFT_LEFT, SHIFT_RIGHT, DROP_KEY, SWAP_KEY, DRAG_N_DROP]
#     [*] 使用前缀'player:'让玩家执行命令。
#     Click_Commands:
#       LEFT:
#       - say Hello
#       - give %player_name% diamond 1
#       - player: warp shop
# ==================================================
Settings:
  MenuType: generic_9x6
  Title: <black>购物车</black>
  Auto_Refresh: -1
  PlaceholderAPI:
    Enabled: false
Product:
  # 为特定数量注册'add'、'set'和'take'按钮类型。
  # 默认注册'add_1'、'add_8'、'add_16'、'add_32'、'add_64'按钮类型（'set'和'take'类型相同）。
  Amount_Buttons: 1,8,16,32,64
  Slots: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35
  # 设置使用数量按钮时播放的声音。
  Sound: entity.item.pickup;1.0;1.0
Content:
  confirm:
    Priority: 50
    Item:
      Material: minecraft:player_head
      Display_Name: <lgreen><b>确认</b></lgreen>
      Lore:
      - <lgreen><b>详情:</b></lgreen>
      - '<lgreen>▪ <lgray>数量: </lgray>%units%</lgreen>'
      - '<lgreen>▪ <lgray>总计: </lgray>%amount%</lgreen>'
      - '<lgreen>▪ <lgray>价格: </lgray>%price%</lgreen>'
      - '<lgreen>▪ <lgray>余额: </lgray>%balance%</lgreen>'
      SkinURL: a79a5c95ee17abfef45c8dc224189964944d560f19a44f19f8a46aef3fee4756
    Slots: '53'
    Type: confirm
  decline:
    Priority: 50
    Item:
      Material: minecraft:player_head
      Display_Name: <lred><b>取消</b></lred>
      Lore: []
      SkinURL: 27548362a24c0fa8453e4d93e68c5969ddbde57bf6666c0319c1ed1e84d89065
    Slots: '45'
    Type: decline
  black_stained_glass_pane:
    Priority: 0
    Item:
      Material: minecraft:black_stained_glass_pane
      Lore: []
    Slots: 46,47,48,49,50,51,52
    Type: 'null'
  add_1:
    Priority: 0
    Item:
      Material: minecraft:player_head
      Display_Name: <lgreen><b>+1</b></lgreen>
      Lore: []
      SkinURL: 6d65ce83f1aa5b6e84f9b233595140d5b6beceb62b6d0c67d1a1d83625ffd
    Slots: '42'
    Type: add_1
  add_8:
    Priority: 0
    Item:
      Material: minecraft:player_head
      Display_Name: <lgreen><b>+8</b></lgreen>
      Lore: []
      SkinURL: f2ee1371d8f0f5a8b759c291863d704adc421ad519f17462b87704dbf1c78a4
    Slots: '43'
    Type: add_8
  add_16:
    Priority: 0
    Item:
      Material: minecraft:player_head
      Display_Name: <lgreen><b>+16</b></lgreen>
      Lore: []
      SkinURL: 19f62a469a206add73887c7366376a6c4f3377b2f5b979351e96ac634572
    Slots: '44'
    Type: add_16
  take_1:
    Priority: 0
    Item:
      Material: minecraft:player_head
      Display_Name: <lred><b>-1</b></lred>
      Lore: []
      SkinURL: 8d2454e4c67b323d5be953b5b3d54174aa271460374ee28410c5aeae2c11f5
    Slots: '36'
    Type: take_1
  take_8:
    Priority: 0
    Item:
      Material: minecraft:player_head
      Display_Name: <lred><b>-8</b></lred>
      Lore: []
      SkinURL: 1683440c6447c195aaf764e27a1259219e91c6d8ab6bd89a11ca8d2cc799fa8
    Slots: '37'
    Type: take_8
  take_16:
    Priority: 0
    Item:
      Material: minecraft:player_head
      Display_Name: <lred><b>-16</b></lred>
      Lore: []
      SkinURL: ae3e4bc71e3ac330836181eda96bc6f128e5c5313ab952c8ff6ded549e13a5
    Slots: '38'
    Type: take_16
  set_1:
    Priority: 0
    Item:
      Material: minecraft:player_head
      Display_Name: <lblue><b>设为 1</b></lblue>
      Lore: []
      SkinURL: bd21b0bafb89721cac494ff2ef52a54a18339858e4dca99a413c42d9f88e0f6
    Slots: '39'
    Type: set_1
  set_max:
    Priority: 0
    Item:
      Material: minecraft:player_head
      Display_Name: <lblue><b>设为最大值</b></lblue>
      Lore: []
      SkinURL: d5e1be33374fd7b2bae9c8fc9146b6ed3eedcb1476b3b7b8010f5f44bfa843e
    Slots: '40'
    Type: set_max
  set_custom:
    Priority: 0
    Item:
      Material: minecraft:player_head
      Display_Name: <lblue><b>自定义数量</b></lblue>
      Lore: []
      SkinURL: 117f3666d3cedfae57778c78230d480c719fd5f65ffa2ad3255385e433b86e
    Slots: '41'
    Type: set_custom