Name: 建筑方块  # 商店名称
Description:  # 商店描述
- <lgray>寻找您最喜欢的物品来</lgray>
- <lgray>建造和制作您最好的建筑。</lgray>
- ' '
- <c:#15A2DD>→ <b><u>点击</u></b> 浏览</c>
Icon:  # 图标设置
  Material: minecraft:player_head  # 材质：玩家头颅
  Display_Name: <c:#15A2DD><b>建筑方块</b></c>  # 显示名称
  Lore: []  # 物品说明（空）
  SkinURL: 99ddfda73dd88c669b62f6a0baea91c3c688df55d65e812fec8782ab87497c4d  # 皮肤URL
Pages: 12  # 页面数量
Permission_Required: false  # 是否需要权限
Transaction_Allowed:  # 允许的交易类型
  BUY: true   # 允许购买
  SELL: true  # 允许出售
MainMenu:  # 主菜单设置
  Slot: 11  # 槽位编号
Aliases: []  # 别名（空）
Layout:  # 布局设置
  Name: default  # 布局名称：默认

