# 商店系统设置配置文件
Rent:
  # 控制商店租赁功能是否启用
  Enabled: true
  # 设置租赁时长的限制值
  # [*] 使用 -1 表示无限制
  MaxDuration: 60
  # 为每种货币设置租赁价格限制
  # [*] 使用 -1 表示无限制
  MaxPrice:
    vault: 10000.0
Shops:
  # 设置商店变更保存（写入）到配置文件的频率（秒）
  # [异步操作]
  # [默认值为30]
  Save_Interval: 30
  # 为管理员商店设置自定义商店主名称
  AdminShop_Name: 管理员商店
  # 默认商店名称，将在创建商店时使用
  Default_Name: 商店
  # 设置商店名称的最大长度限制
  # 有助于防止玩家为其商店设置过于冗长的名称
  Max_Name_Length: 12
  # 设置默认商品购买菜单配置
  # 您可以在 /menu/product_carts/ 目录中创建和编辑购物车界面
  Default_Cart_UI: default
  # 控制插件是否应在玩家传送到商店之前检查商店位置的安全性
  Check_Safe_Location: true
  # 设置是否自动管理玩家商店银行而无需手动操作
  # 这意味着玩家将在其商店的每次交易中立即获得/失去资金
  Auto_Bank: true
  # 设置当玩家离线时，插件是否直接从/向商店所有者账户提取/存入货币，
  # 而不是使用商店银行
  #
  # 为什么？即使启用了'Auto_Bank'选项，玩家也无法向离线所有者的商店出售物品，
  # 除非商店银行中有足够的资金。
  # 此设置将绕过该限制。
  #
  # [*] 此功能可能影响性能（取决于货币插件及其离线玩家数据处理）
  # [*] 此功能不适用于某些货币
  OfflineTransactions: false
  InfiniteStorage:
    # 设置是否启用无限存储系统
    # 无限存储允许您在商店中存储任意数量的物品，
    # 并且不使用方块库存
    Enabled: false
  Product:
    InitialPrice:
      # 为箱子商店中添加的新商品设置初始购买价格
      Buy: 10.0
      # 为箱子商店中添加的新商品设置初始销售价格
      Sell: 2.0
  ItemCreation:
    # 设置玩家是否可以通过放置特定物品来创建商店
    Enabled: false
  Creation:
    Cost:
      # 设置玩家创建箱子商店需要支付的金额
      Create: 0.0
      # 设置玩家移除箱子商店需要支付的金额
      Remove: 0.0
    # 不允许创建箱子商店的世界列表
    World_Blacklist:
    - another_world
    - custom_world
    # 为特定等级/权限设置可拥有的商店数量
    # 使用 '-1' 表示无限制
    Max_Shops_Per_Rank:
      # 可用值: RANK, PERMISSION
      # ==================== 等级模式 ====================
      # 通过玩家的权限组获取值。'Values'列表中的所有键将代表权限组名称。
      # 如果玩家没有指定的任何组，则将使用'Default_Value'设置
      #   Values:
      #     vip: 1 # -> 玩家必须在'vip'权限组中
      #     gold: 2 # -> 玩家必须在'gold'权限组中
      #     emerald: 3 # -> 玩家必须在'emerald'权限组中
      #
      # ==================== 权限模式 ====================
      # 通过玩家权限获取值。'Values'列表中的所有键将代表'Permission_Prefix'设置的后缀（见下方）。
      # 如果玩家没有指定的任何权限，则将使用'Default_Value'设置
      #   Permission_Prefix: 'example.prefix.'
      #   Values:
      #     vip: 1 # -> 玩家必须拥有'example.prefix.vip'权限
      #     gold: 2 # -> 玩家必须拥有'example.prefix.gold'权限
      #     emerald: 3 # -> 玩家必须拥有'example.prefix.emerald'权限
      Mode: RANK
      # 为'PERMISSION'模式设置权限前缀
      Permission_Prefix: excellentshop.chestshop.shops.amount.
      Default_Value: 10
      Values:
        vip: 20
        admin: -1
    # 设置插件是否将模拟方块放置以确保玩家可以在那里创建商店
    # 此设置应该作为与领地/保护插件的通用兼容性解决方案
    # 只有在遇到重大问题时才禁用此选项
    Check_Build_Access: true
    In_Player_Claims_Only:
      # 设置玩家是否只能在自己的领地中创建商店
      # 支持的插件: Lands, GriefPrevention, WorldGuard, Kingdoms
      Enabled: false
  Products:
    # 设置特定等级/权限的玩家可以同时在商店中放入多少商品
    # 使用 '-1' 表示无限制
    Max_Products_Per_Shop:
      # 可用值: RANK, PERMISSION
      # ==================== 等级模式 ====================
      # 通过玩家的权限组获取值。'Values'列表中的所有键将代表权限组名称。
      # 如果玩家没有指定的任何组，则将使用'Default_Value'设置
      #   Values:
      #     vip: 1 # -> 玩家必须在'vip'权限组中
      #     gold: 2 # -> 玩家必须在'gold'权限组中
      #     emerald: 3 # -> 玩家必须在'emerald'权限组中
      #
      # ==================== 权限模式 ====================
      # 通过玩家权限获取值。'Values'列表中的所有键将代表'Permission_Prefix'设置的后缀（见下方）。
      # 如果玩家没有指定的任何权限，则将使用'Default_Value'设置
      #   Permission_Prefix: 'example.prefix.'
      #   Values:
      #     vip: 1 # -> 玩家必须拥有'example.prefix.vip'权限
      #     gold: 2 # -> 玩家必须拥有'example.prefix.gold'权限
      #     emerald: 3 # -> 玩家必须拥有'example.prefix.emerald'权限
      Mode: RANK
      # 为'PERMISSION'模式设置权限前缀
      Permission_Prefix: excellentshop.chestshop.products.amount.
      Default_Value: 3
      Values:
        vip: 5
        admin: -1
    # 启用后，在箱子商店中添加的所有商品都将以1个数量添加，无论玩家使用的堆叠数量如何
    New_Products_Single_Amount: false
    # 不能作为商店商品添加的物品列表
    # 原版名称: https://minecraft.wiki/w/Java_Edition_data_values -> Blocks / Items -> Resource location column.
    # 支持的插件: ExcellentCrates, ExecutableItems, ItemsAdder, MMOItems, Nexo, Oraxen
    Material_Blacklist:
    - custom_item_123
    - barrier
    # 在其描述中包含以下词语的物品将被禁止用作商店商品
    Lore_Blacklist:
    - ass hole bitch
    - fuck
    # 在其名称中包含以下词语的物品将被禁止用作商店商品
    Name_Blacklist:
    - sample text
    - shit
    Format:
      # 商品描述格式。使用 '%lore%' 占位符插入商品物品的原始描述
      # 您可以使用'箱子商品'占位符: https://nightexpressdev.com/excellentshop/placeholders
      Main:
      - '%lore%'
      - ''
      - '%buy%'
      - ''
      - '%sell%'
      - ''
      - <dgray>按住 <lgray>Shift</lgray> 快速购买和销售。</dgray>
      # 如果商品可购买时出现的描述
      # 占位符: %buy%
      Buy:
      - <green><b>购买:</b></green>
      - <green>←<white> 左键点击以 </white>%product_price_buy_formatted%<white> 购买</white></green>
      - '<green>✔<white> 剩余物品: </white>%product_stock_global_buy_amount_left%</green>'
      # 如果商品可销售时出现的文本
      # 占位符: %sell%
      Sell:
      - <red><b>销售:</b></red>
      - <red>→<white> 右键点击以 </white>%product_price_sell_formatted%<white> 销售</white></red>
      - <red>→<white> 按 [F] 键以 </white>%product_price_sell_all_formatted%<white> 全部销售</white></red>
      - '<red>✔<white> 商店空间: </white>%product_stock_global_sell_amount_left%</red>'
Display:
  # 设置商店显示为玩家渲染的频率（秒）
  Update_Interval: 1
  # 设置展示柜中显示的物品更换的频率（秒）
  # [*] 必须可被 Update_Interval 值整除
  Item_Change_Interval: 5
  # 设置商店显示的可见距离
  Visible_Distance: 10
  # 使用盔甲架实体来显示全息图和展示柜，而不是TextDisplay和ItemDisplay
  # [*] 仅在遇到兼容性问题时启用
  UseArmorStands: false
  Hologram:
    # 控制商店是否显示客户端全息图以显示其名称和价格
    Enabled: true
    # 设置全息图行之间的距离
    LineGap: 0.3
    # 用于分割行的最大行宽
    # [*] 目前不支持行分割。调整全息图格式以避免分割
    # [默认值为200]
    LineWidth: 200
    # 渲染文本的alpha值。值范围从0到255。最多3的值被视为完全不透明（255）
    # 对于4到26之间的值，文本渲染被丢弃。默认为-1，代表255且完全不透明
    # [默认值为-1]
    TextOpacity: -1
    # 文本是否透过方块可见
    # [默认值为false]
    SeeThrough: false
    # 文本是否带有阴影显示
    # [默认值为true]
    Shadow: true
    # 背景颜色，按[A,R,G,B]排列。其中: A = Alpha（不透明度），R = 红色，G = 绿色，B = 蓝色
    # [默认值为64,0,0,0]
    BackgroundColor: 64,0,0,0
    Text:
      # 管理员商店的全息图文本格式
      # 占位符:
      # - 箱子商店占位符: https://nightexpressdev.com/excellentshop/placeholders
      # - 箱子商品占位符: https://nightexpressdev.com/excellentshop/placeholders
      # - PlaceholderAPI
      AdminShop:
      - <lyellow><b>%shop_name%</b></lyellow>
      - <lgray>%product_preview_name%</lgray>
      - '%buy% %sell%'
      # 玩家商店的全息图文本格式
      # - 箱子商店占位符: https://nightexpressdev.com/excellentshop/placeholders
      # - 箱子商品占位符: https://nightexpressdev.com/excellentshop/placeholders
      # - PlaceholderAPI
      PlayerShop:
      - <lyellow><b>%shop_name%</b></lyellow>
      - <lgray>%product_preview_name%</lgray>
      - '%buy% %sell%'
      - '<lgray>库存: <lyellow>%product_amount%</lyellow></lgray>'
      # 设置为租赁的商店的全息图文本
      Rent:
      - <lyellow><b>待租赁</b></lyellow>
      - <lgray>%shop_rent_duration%</lgray>
      - <lgray>%shop_rent_price%</lgray>
      # 没有添加商品的商店的全息图文本
      Absent:
      - <gray>< 未配置 ></gray>
      # 如果显示的商品可购买时在'%buy%'占位符中使用的文本
      BuyPrice: '<green>购: </green><lgreen>%product_price_buy_formatted%</lgreen>'
      # 如果显示的商品可销售时在'%sell%'占位符中使用的文本
      SellPrice: '<red>售: </red><lred>%product_price_sell_formatted%</lred>'
  Showcase:
    # 以下展示柜将可供玩家为其商店选择
    Catalog:
      ice:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:ice
          Lore: []
      glass:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:glass
          Lore: []
      tinted_glass:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:tinted_glass
          Lore: []
      spawner:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:spawner
          Lore: []
      white_stained_glass:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:white_stained_glass
          Lore: []
      lime_stained_glass:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:lime_stained_glass
          Lore: []
      gray_stained_glass:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:gray_stained_glass
          Lore: []
      black_stained_glass:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:black_stained_glass
          Lore: []
      blue_stained_glass:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:blue_stained_glass
          Lore: []
      brown_stained_glass:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:brown_stained_glass
          Lore: []
      cyan_stained_glass:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:cyan_stained_glass
          Lore: []
      green_stained_glass:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:green_stained_glass
          Lore: []
      light_blue_stained_glass:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:light_blue_stained_glass
          Lore: []
      light_gray_stained_glass:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:light_gray_stained_glass
          Lore: []
      magenta_stained_glass:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:magenta_stained_glass
          Lore: []
      orange_stained_glass:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:orange_stained_glass
          Lore: []
      pink_stained_glass:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:pink_stained_glass
          Lore: []
      purple_stained_glass:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:purple_stained_glass
          Lore: []
      red_stained_glass:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:red_stained_glass
          Lore: []
      yellow_stained_glass:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:yellow_stained_glass
          Lore: []
      copper_grate:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:copper_grate
          Lore: []
      exposed_copper_grate:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:exposed_copper_grate
          Lore: []
      oxidized_copper_grate:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:oxidized_copper_grate
          Lore: []
      waxed_copper_grate:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:waxed_copper_grate
          Lore: []
      waxed_exposed_copper_grate:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:waxed_exposed_copper_grate
          Lore: []
      waxed_oxidized_copper_grate:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:waxed_oxidized_copper_grate
          Lore: []
      waxed_weathered_copper_grate:
        Name: '%type%'
        DisplayBlock:
          Material: minecraft:waxed_weathered_copper_grate
          Lore: []
Transaction_Logs:
  Output:
    File: true
    Console: true
  Format:
    Date: dd/MM/yyyy HH:mm:ss
    Purchase: '%type%: %player_name% - x%amount% 个 %item% 以 %price% 在 %shop_name% 商店购买。 [%shop_location_x%, %shop_location_y%, %shop_location_z% 位于 %shop_location_world%，所有者为 %shop_owner%]'