DataFixer:
  MissingVersion: 4189
  UnknownVersion: 10000
Menu:
  # 设置玩家在 GUI 中点击的冷却时间（毫秒）。
  # [默认 150 毫秒]
  Click_Cooldown: 150
UserData:
  Cache:
    # [已过时，已移至各插件的 engine.yml]
    LifeTime: 300
Time:
  # 设置插件使用的时区，以便正确处理本地日期和时间。
  TimeZone: Asia/Shanghai
Engine:
  # 允许在插件配置文件中使用旧版颜色代码（如 '&7'、'&l' 等）。
  # 此设置仅为向后兼容存在！未来更新不保证继续支持！
  # 除非您确实需要为自定义语言配置和翻译支持旧代码，否则不应启用。
  # 请尽快迁移到新的文本格式：https://nightexpressdev.com/nightcore/configuration/text-formation/
  Legacy_Color_Support: true
Number:
  # 控制数值数据的格式化与舍入方式。
  # 允许的模式：UP, DOWN, CEILING, FLOOR, HALF_UP, HALF_DOWN, HALF_EVEN, UNNECESSARY
  # 教程：https://docs.oracle.com/javase/tutorial/i18n/format/decimalFormat.html
  Format:
    Format: '#,###.###'
    Rounding: HALF_EVEN
    Locale: zh-CN
  # 设置数字简写的步进倍数。
  # 当数字将被压缩时，会除以该值来判断是否落入某个数字简写范围。
  # [默认 1000]
  Shortcut_Step: 1000
  # 自定义数字简写。
  Shortcut_List:
    thousand:
      Magnitude: 1
      Name: k
    million:
      Magnitude: 2
      Name: m
    billion:
      Magnitude: 3
      Name: b
    trillion:
      Magnitude: 4
      Name: t
    quadrillion:
      Magnitude: 5
      Name: q
Profiles:
  Cache:
    # 设置已缓存玩家档案的过期时间（分钟），过期后会向 Mojang API 请求更新名称与纹理。
    # [*] 自定义头颅皮肤的档案不会更新。
    # [*] 每次查询档案时重置过期时间。
    # [*] 设为 -1 则直到服务器重启前不更新。
    # [默认 360（6 小时）]
    UpdateTime: 360
    # 设置已缓存玩家档案的清理时间（分钟），过期后将从缓存与内存中移除。
    # [*] 自定义头颅皮肤的档案不会被清理。
    # [*] 每次查询档案时重置过期时间。
    # [*] 设为 -1 则直到服务器重启前不清理。
    # [默认 1440（24 小时）]
    PurgeTime: 1440
  # 每隔多少秒清理一次已缓存的玩家档案。
  # [默认 600（10 分钟）]
  PurgeInterval: 600
  # 控制当档案所有者加入服务器时是否强制更新缓存的玩家档案。
  # [默认 true]
  UpdateOnJoin: true
  # 控制带自定义纹理的档案是否可以查询 Mojang API 以获取缺失的属性。
  # [*] 仅当遇到自定义头颅纹理加载问题时才启用。
  # [*] 启用可能导致被 Mojang 限流。
  # [默认 false]
  FetchCustom: false