# ==================== [设置] 配置段 ====================
# > [MenuType] : 字符串 | 代表菜单类型。允许的值: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/MenuType.html
# > [Title] : 字符串 | 设置菜单标题。
# > [Auto_Refresh] : 整数 | 定义菜单刷新频率（秒）。设置为0禁用。
# > [PlaceholderAPI -> Enabled] : 布尔值 | 启用后，为菜单中的所有物品应用PlaceholderAPI占位符（每个玩家）。
#  
# ==================== [内容] 配置段 ====================
# 您可以在此部分自由编辑物品（添加、删除、修改物品）。
# > [Item] : 段落 | 要显示的物品。
#     [*] 导航到 https://nightexpressdev.com/nightcore/configuration/item-formation/ 查看可用选项列表。
# > [Priority] : 整数 | 物品优先级。较高的值将覆盖相同槽位中的其他物品。
# > [Slots] : 整数数组 | 物品槽位，从0开始。用逗号分隔。
#     Slots: '0,4,9,10'
# > [Type] : 字符串 | 定义物品点击操作。
#     [*] 可用类型: ['close', 'return', 'page_next', 'page_previous', 'sell_all']
# > [Click_Commands] : 段落 | 点击时执行命令，支持PlaceholderAPI。
#     [*] 仅在[Type]未设置（null）时有效。
#     [*] 可用点击类型: [LEFT, RIGHT, SHIFT_LEFT, SHIFT_RIGHT, DROP_KEY, SWAP_KEY, DRAG_N_DROP]
#     [*] 使用前缀'player:'让玩家执行命令。
#     Click_Commands:
#       LEFT:
#       - say Hello
#       - give %player_name% diamond 1
#       - player: warp shop
# ==================================================
Settings:
  MenuType: generic_9x6
  Title: <c:#3E3E3E>商店 → %shop_name% (<white>%page%</white>/<white>%pages%</white>)</c>
  Auto_Refresh: -1
  PlaceholderAPI:
    Enabled: true
Content:
  gray_stained_glass_pane:
    Priority: -1
    Item:
      Material: minecraft:gray_stained_glass_pane
      Lore: []
      Hide_Tooltip: true
    Slots: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53
    Type: 'null'
  return:
    Priority: 10
    Item:
      Material: minecraft:iron_door
      Display_Name: <white><u>返回</u></white>
      Lore:
      - '%empty-if-above%'
      - '%empty-if-below%'
    Slots: '49'
    Type: return
  page_next:
    Priority: 10
    Item:
      Material: minecraft:arrow
      Display_Name: <lyellow><u>下一页</u> →</lyellow>
      Lore:
      - '%empty-if-above%'
      - '%empty-if-below%'
    Slots: '50'
    Type: page_next
  page_previous:
    Priority: 10
    Item:
      Material: minecraft:arrow
      Display_Name: <lyellow>← <u>上一页</u></lyellow>
      Lore:
      - '%empty-if-above%'
      - '%empty-if-below%'
    Slots: '48'
    Type: page_previous
  sell_all:
    Priority: 10
    Item:
      Material: minecraft:player_head
      Display_Name: <c:#ebd12a><b>全部出售</b></c>
      Lore:
      - <lgray>将您背包中的所有物品</lgray>
      - <lgray>出售给所有可用的商店。</lgray>
      - ''
      - '<lgray><c:#ebd12a>➥</c> 出售倍率: <c:#ebd12a>x%sell_multiplier%</c></lgray>'
      - ''
      - <c:#ebd12a>→ <b><u>点击</u></b> 出售</c>
      SkinURL: 9fd108383dfa5b02e86635609541520e4e158952d68c1c8f8f200ec7e88642d
    Slots: '52'
    Type: sell_all
  player_head:
    Priority: 10
    Item:
      Material: minecraft:player_head
      Display_Name: <c:#7cf1de><b>余额</b></c>
      Lore:
      - <lgray>这里显示您拥有</lgray>
      - <lgray>多少金币。</lgray>
      - ''
      - <c:#7cf1de>➥</c> <white>%balance%</white>
      SkinURL: 3324a7d61ccd44b031744b517f911a5c461614b953b17f648282e147b29d10e
    Slots: '46'
    Type: 'null'