Name: 红石  # 商店名称
Description:  # 商店描述
- <lgray>您喜欢玩红石吗？</lgray>
- ' '
- <c:#D93636>→ <b><u>点击</u></b> 浏览</c>
Icon:  # 图标设置
  Material: minecraft:player_head  # 材质：玩家头颅
  Display_Name: <c:#D93636><b>红石</b></c>  # 显示名称
  Lore: []  # 物品说明（空）
  SkinURL: c168291abac4a5f86fe8b360338986aee7abcb7f4b8169eb55dfec928561258  # 皮肤URL
Pages: 1  # 页面数量
Permission_Required: false  # 是否需要权限
Transaction_Allowed:  # 允许的交易类型
  BUY: true   # 允许购买
  SELL: true  # 允许出售
MainMenu:  # 主菜单设置
  Slot: 24  # 槽位编号
Aliases: []  # 别名（空）
Layout:  # 布局设置
  Name: default  # 布局名称：默认