Name: 杂项  # 商店名称
Description:  # 商店描述
- <lgray>这里有一些稀有</lgray>
- <lgray>和随机的物品。</lgray>
- ' '
- <c:#B240CE>→ <b><u>点击</u></b> 浏览</c>
Icon:  # 图标设置
  Material: minecraft:player_head  # 材质：玩家头颅
  Display_Name: <c:#B240CE><b>杂项</b></c>  # 显示名称
  Lore: []  # 物品说明（空）
  SkinURL: e02eace744e0c913778fe8b35e13e3b0549d459ae713dfc480a2b41073cd7492  # 皮肤URL
Pages: 2  # 页面数量
Permission_Required: false  # 是否需要权限
Transaction_Allowed:  # 允许的交易类型
  BUY: true   # 允许购买
  SELL: true  # 允许出售
MainMenu:  # 主菜单设置
  Slot: 15  # 槽位编号
Aliases: []  # 别名（空）
Layout:  # 布局设置
  Name: default  # 布局名称：默认
