Name: 战斗工具  # 商店名称
Description:  # 商店描述
- <lgray>您需要PvP装备</lgray>
- <lgray>或一些工具吗？</lgray>
- ' '
- <c:#7FEFD0>→ <b><u>点击</u></b> 浏览</c>
Icon:  # 图标设置
  Material: minecraft:player_head  # 材质：玩家头颅
  Display_Name: <c:#7FEFD0><b>战斗与工具</b></c>  # 显示名称
  Lore: []  # 物品说明（空）
  SkinURL: f20cca630a71638f646ab5ab7ff053951e796d8559f816152e11560588fd501c  # 皮肤URL
Pages: 3  # 页面数量
Permission_Required: false  # 是否需要权限
Transaction_Allowed:  # 允许的交易类型
  BUY: true   # 允许购买
  SELL: true  # 允许出售
MainMenu:  # 主菜单设置
  Slot: 23  # 槽位编号
Aliases: []  # 别名（空）
Layout:  # 布局设置
  Name: default  # 布局名称：默认
