Name: 怪物掉落物  # 商店名称
Description:  # 商店描述
- <lgray>通过击杀或驯养怪物</lgray>
- <lgray>来赚钱并出售它们的掉落物。</lgray>
- ' '
- <c:#D7BB9A>→ <b><u>点击</u></b> 浏览</c>
Icon:  # 图标设置
  Material: minecraft:player_head  # 材质：玩家头颅
  Display_Name: <c:#D7BB9A><b>怪物掉落物</b></c>  # 显示名称
  Lore: []  # 物品说明（空）
  SkinURL: f26bde45049c7b7d34605d806a06829b6f955b856a5991fd33e7eabce44c0834  # 皮肤URL
Pages: 2  # 页面数量
Permission_Required: false  # 是否需要权限
Transaction_Allowed:  # 允许的交易类型
  BUY: true   # 允许购买
  SELL: true  # 允许出售
MainMenu:  # 主菜单设置
  Slot: 14  # 槽位编号
Aliases: []  # 别名（空）
Layout:  # 布局设置
  Name: default  # 布局名称：默认
