Name: 矿物  # 商店名称
Description:  # 商店描述
- <lgray>珍贵的矿物正在出售。</lgray>
- ' '
- <c:#91F0FF>→ <b><u>点击</u></b> 浏览</c>
Icon:  # 图标设置
  Material: minecraft:player_head  # 材质：玩家头颅
  Display_Name: <c:#91F0FF><b>矿物</b></c>  # 显示名称
  Lore: []  # 物品说明（空）
  SkinURL: 2c21799fdb23ea44432d6a449c747d3bbd566cc29392c0fe3153a9ddca5e5d5  # 皮肤URL
Pages: 2  # 页面数量
Permission_Required: false  # 是否需要权限
Transaction_Allowed:  # 允许的交易类型
  BUY: true   # 允许购买
  SELL: true  # 允许出售
MainMenu:  # 主菜单设置
  Slot: 20  # 槽位编号
Aliases: []  # 别名（空）
Layout:  # 布局设置
  Name: default  # 布局名称：默认
