_dataver: 414
General:
  # 设置默认商品购买菜单配置。
  # 您可以在/menu/product_carts/目录中创建和编辑购物车界面。
  Default_Cart_UI: default
  # 设置虚拟商店是否对购买和出售使用不同的购买菜单。
  Split_BuySell_Cart_UI: false
  # 如果启用拆分选项，设置购买的默认商品购买菜单配置。
  # 您可以在/menu/product_carts/目录中创建和编辑购物车界面。
  Default_Buy_Cart_UI: default
  # 如果启用拆分选项，设置出售的默认商品购买菜单配置。
  # 您可以在/menu/product_carts/目录中创建和编辑购物车界面。
  Default_Sell_Cart_UI: default
  # 设置默认商店布局配置，以防商店原有配置不再存在。
  Default_Layout: default
  Main_Menu:
    # 启用主菜单功能，您可以在其中列出所有虚拟商店。
    Enabled: true
    # 启用时，从主菜单中隐藏玩家无权访问的商店。
    Hide_No_Permission_Shops: true
  Shop_Shortcut:
    # 启用商店快捷方式和商店别名命令功能。允许快速打开商店。
    Enabled: true
    # 快速主菜单和商店访问的命令别名。
    # 用逗号分隔。
    Commands: shop
  Sell_Menu:
    # 当为'true'时启用出售菜单功能，您可以在其中快速出售所有物品。
    Enabled: true
    # 设置出售菜单是否应该简化。
    # 当简化时，不执行物品和点击验证，因此菜单就像普通箱子一样，
    # 物品将在关闭时出售而不是按钮点击。
    Simplified: false
    # 打开出售菜单的自定义命令别名。用逗号分隔。
    Commands: sellgui,sellmenu
  Sell_All:
    # 启用一键出售命令功能。
    Enabeled: true
    # 一键出售命令别名。用逗号分隔。
    Commands: sellall
  Sell_Hand:
    # 启用出售手持物功能。
    Enabled: true
    # 出售手持物命令别名。用逗号分隔。
    Commands: sellhand
  Sell_Hand_All:
    # 启用出售所有手持物功能。
    Enabled: true
    # 出售所有手持物命令别名。用逗号分隔。
    Commands: sellhandall
  # 在这里您可以为特定等级定义出售倍率。
  # 如果您想使用基于权限的系统，可以使用'excellentshop.virtual.sellmultiplier.[name]'权限模式。
  # (确保使用与您的权限等级不同的名称)
  # 公式: '<sellPrice> * <sellMultiplier>'。所以，1.0 = 100%（无变化），1.5 = +50%，0.75 = -25%，等等。
  Sell_Multipliers:
    # 可用值: RANK, PERMISSION
    # ==================== 等级模式 ====================
    # 通过玩家的权限组获取值。'Values'列表中的所有键将代表权限组名称。
    # 如果玩家没有指定的任何组，则将使用'Default_Value'设置
    #   Values:
    #     vip: 1 # -> 玩家必须在'vip'权限组中。
    #     gold: 2 # -> 玩家必须在'gold'权限组中。
    #     emerald: 3 # -> 玩家必须在'emerald'权限组中。
    #
    # ==================== 权限模式 ====================
    # 通过玩家的权限获取值。'Values'列表中的所有键将代表'Permission_Prefix'设置的后缀（见下文）。
    # 如果玩家没有指定的任何权限，则将使用'Default_Value'设置
    #   Permission_Prefix: 'example.prefix.'
    #   Values:
    #     vip: 1 # -> 玩家必须有'example.prefix.vip'权限。
    #     gold: 2 # -> 玩家必须有'example.prefix.gold'权限。
    #     emerald: 3 # -> 玩家必须有'example.prefix.emerald'权限。
    Mode: RANK
    # 为'PERMISSION'模式设置权限前缀。
    Permission_Prefix: excellentshop.virtual.sellmultiplier.
    Default_Value: 1.0
    Values:
      gold: 2.0
      vip: 1.5
  # 玩家不能在指定游戏模式下使用商店。
  # 可用值: CREATIVE, SURVIVAL, ADVENTURE, SPECTATOR
  Disabled_In_Gamemodes:
  - CREATIVE
  # 玩家不能在指定世界中使用商店。区分大小写。
  Disabled_In_Worlds:
  - world_name
  - example_world123
SellFeatures:
  Containers:
    # 控制'容器'物品的内容是否包含在一键出售、出售界面功能中，例如潜影盒、箱子等。
    # [*] 尚不包括Bundle。
    ContentIncluded: true
GUI:
  Shop_Format:
    # 为主菜单中的商店物品设置显示名称。
    # 您可以使用'虚拟商店'占位符:https://nightexpressdev.com/excellentshop/placeholders
    Name: '%shop_icon_name%'
    # 为主菜单中的商店物品设置描述。
    # 您可以使用'虚拟商店'占位符: https://nightexpressdev.com/excellentshop/placeholders
    Lore:
    - '%shop_description%'
  Product_Format:
    Lore:
      # 商品描述格式。使用'%lore%'占位符插入商品物品的原始描述。
      # 您可以使用'虚拟商品'占位符: https://nightexpressdev.com/excellentshop/placeholders
      Main:
      - '%permission%'
      - '%discount%'
      - '%empty-if-above%'
      - '%lore%'
      - '%empty-if-above%'
      - '%buy%'
      - '%empty-if-above%'
      - '%sell%'
      - '%empty-if-above%'
      - <dgray>按住 <lgray>Shift</lgray> 快速购买和出售。</dgray>
      # 如果商品可购买将出现的描述。
      # 占位符: %buy%
      Buy:
      - <green><b>购买:</b></green>
      - <green>←<white> 左键点击以 </white>%product_price_buy_formatted%<white> 购买</white></green>
      - '%empty-if-below%'
      - '%price_dynamic_buy%'
      - '%empty-if-above%'
      - '%stock_global_buy%'
      - '%stock_player_buy%'
      # 如果商品可出售将出现的文本。
      # 占位符: %sell%
      Sell:
      - <red><b>出售:</b></red>
      - <red>→<white> 右键点击以 </white>%product_price_sell_formatted%<white> 出售</white></red>
      - <red>→<white> 按 [F] 以 </white>%product_price_sell_all_formatted%<white> 出售全部</white></red>
      - '%empty-if-below%'
      - '%price_dynamic_sell%'
      - '%empty-if-above%'
      - '%stock_global_sell%'
      - '%stock_player_sell%'
      # 如果商品有有效折扣将出现的文本。
      # 要插入的占位符: %discount%
      Discount:
      - <gray><green>✔</green> 折扣 <green><b>%product_discount_amount%%</b></green>!</gray>
      # 如果玩家无权访问商品将出现的文本。
      # 要插入的占位符: %permission%
      NoPermission:
      - <gray><red>✘</red> 您无权访问此物品!</gray>
      # 当商品具有动态/浮动价格时出现的文本。
      # 要插入的占位符:
      # %price_dynamic_buy%
      # %price_dynamic_sell%
      PriceDynamics:
        SELL:
        - '<red>[?]<white> 平均价格: </white>%product_price_avg_sell%<white> | 动态: </white>%product_price_avg_diff_sell%</red>'
        BUY:
        - '<green>[?]<white> 平均价格: </white>%product_price_avg_buy%<white> | 动态: </white>%product_price_avg_diff_buy%</green>'
      Stock:
        GLOBAL:
          # 当商品配置了购买/出售库存时出现的文本。
          # 要插入的占位符:
          # %stock_global_buy%
          BUY:
          - '<green>● <white>库存: </white>%product_stock_global_buy_amount_left%<white>/</white>%product_stock_global_buy_amount_initial%</green><gray> (<white>%product_stocks_restock_date%</white>)</gray>'
          # 当商品配置了购买/出售库存时出现的文本。
          # 要插入的占位符:
          # %stock_global_sell%
          SELL:
          - '<red>● <white>库存: </white>%product_stock_global_sell_amount_left%<white>/</white>%product_stock_global_sell_amount_initial%</red><gray> (<white>%product_stocks_restock_date%</white>)</gray>'
        PLAYER:
          # 当商品配置了购买/出售限制时出现的文本。
          # 要插入的占位符:
          # %stock_player_buy%
          BUY:
          - '<green>● <white>您的限制: </white>%product_stock_player_buy_amount_left%<white>/</white>%product_stock_player_buy_amount_initial%</green><gray> (<white>%product_limits_restock_date%</white>)</gray>'
          # 当商品配置了购买/出售限制时出现的文本。
          # 要插入的占位符:
          # %stock_player_sell%
          SELL:
          - '<red>● <white>您的限制: </white>%product_stock_player_sell_amount_left%<white>/</white>%product_stock_player_sell_amount_initial%</red><gray> (<white>%product_limits_restock_date%</white>)</gray>'
Transaction_Logs:
  Output:
    File: true
    Console: true
  Format:
    Date: dd/MM/yyyy HH:mm:ss
    Purchase: '%type%: %player_name% - x%amount% 个 %item% 以 %price% 在 %shop_name% 商店中.'